<?php

namespace App\Models;

use App\Models\Scopes\OnlyCurrentOwner;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class Appointment extends Model
{
    /** @use HasFactory<\Database\Factories\AppointmentFactory> */
    use HasFactory;


    protected $guarded = [];

    protected static function booted()
    {
        parent::booted(); // TODO: Change the autogenerated stub
        self::addGlobalScope(OnlyCurrentOwner::class);
    }

    public function user():BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    public function customer():BelongsTo
    {
        return $this->belongsTo(Customer::class);
    }

    public function service():BelongsTo
    {
        return $this->belongsTo(Service::class);
    }




}
