<?php

namespace App\Models;

use App\Models\Scopes\OnlyCurrentOwner;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Customer extends Model
{
    /** @use HasFactory<\Database\Factories\CustomerFactory> */
    use HasFactory;


    protected $guarded = [];

    protected static function booted()
    {
        parent::booted(); // TODO: Change the autogenerated stub
        self::addGlobalScope(OnlyCurrentOwner::class);
    }


    public function user():BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    public function messages():HasMany
    {
        return $this->hasMany(Message::class);
    }

    public function appointments():HasMany
    {
        return $this->hasMany(Appointment::class);
    }
}
